os:
  - linux

language: android

env:
  global:
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3

android: 
  components:
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - tools
  - platform-tools
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-android-support

before_install:
    - yes | sdkmanager "platforms;android-$ANDROID_API"
    - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"

sudo: false
jdk: oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

stages:
  - build 
  - name: deploy
    if: branch = master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.pub-cache
    - $HOME/.android/build-cache
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper


before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter build apk --debug
  - ./flutter/bin/flutter build apk --release
deploy:
    provider: releases
    file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/*.apk
    skip_cleanup: true
    if: branch = master
    on:
      tags: true

