os:
  - linux
language: android
  
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter test

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: releases
  file: "./build/app/outputs/apk/PhotoKredy-1.0.0-release.apk"
  skip_cleanup: true
  on:
    tags: true