os:
  - linux

language: android

android: 
  components:
  - build-tools-28.0.3
  - android-27

  
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter build apk

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: releases
  file: "./build/app/outputs/apk/app-release.apk"
  skip_cleanup: true
  on:
    tags: true
