name: photokredy
description: Mobile app providing prepaid phone card fast and easy scanning

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2  

  permission_handler: ^2.2.0 
  preferences: ^1.3.0
  intl_translation: ^0.17.3
  audioplayers: ^0.11.0 

  photokredy_core:
    path: photokredy_core      

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/camera_focus_beep.mp3